package Interface;

import javax.swing.JFileChooser;
import javax.swing.JFrame;

import java.awt.TextArea;
import java.awt.event.ActionEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import javax.swing.BorderFactory;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 73x
 */
public class Acceuil extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public Acceuil() {
        initComponents();
        this.jButton1.setBorder(BorderFactory.createRaisedBevelBorder());
        this.jButton2.setBorder(BorderFactory.createRaisedBevelBorder());
        this.jButton3.setBorder(BorderFactory.createRaisedBevelBorder());
        this.jButton4.setBorder(BorderFactory.createRaisedBevelBorder());
        //this.setContentPane(new Imagef(new ImageIcon("fond.png").getImage()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Joueur VS Joueur");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 120, 200, 35);

        jButton2.setText("Joueur VS IA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 180, 200, 35);

        jButton3.setText("Charger une partie");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 240, 200, 35);

        jButton4.setText("Quitter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });       
        getContentPane().add(jButton4);
        jButton4.setBounds(290, 300, 200, 35);
        
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("Capture.PNG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 800, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    	int x,y;
    	JFrame win=new Saisie();
		//JPanel jpBase=(JPanel) win.getContentPane(); // Récupère le conteneur de la fenêtre
		//setContentPane(jpBase);
		//jpBase.add(S);// Ajoute le composant à la fenêtre
		x=getX();
		y=getY();
		setVisible(false);
		win.setSize(getSize());
        win.setLocation(x, y);
		win.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    	int x,y;
    	JFrame win=new SaisieIa();
		//JPanel jpBase=(JPanel) win.getContentPane(); // Récupère le conteneur de la fenêtre
		//setContentPane(jpBase);
		//jpBase.add(S);// Ajoute le composant à la fenêtre
		x=getX();
		y=getY();
		setVisible(false);		
		win.setSize(getSize());
        win.setLocation(x, y);
		win.setVisible(true);
		dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
		JFileChooser filechoose = new JFileChooser();
		// Créer un JFileChooser
		filechoose.setCurrentDirectory(new File(".")); // Le répertoire
		String approve = new String("Ouvrir");
		int resultatEnregistrer = filechoose.showDialog(filechoose,approve); // Pour afficher le JFileChooser...
		if (resultatEnregistrer == JFileChooser.APPROVE_OPTION) 
		   { String monFichier= new String(filechoose.getSelectedFile().toString());
		// Récupérer le nom du fichier qu'il a spécifié
		if(monFichier.endsWith(".txt")|| monFichier.endsWith(".TXT")) {;}
		// Si ce nom de fichier finit par .txt ou .TXT, ne rien faire et passer à
		else 
		   monFichier = monFichier+ ".txt";
		// Sinon renommer le fichier pour qu'il porte l'extension .txt
		InterfaceAvecC.chargement(monFichier);
		int num=InterfaceAvecC.get_plat_taille();
		AffGrille Jeu=new AffGrille(num, 1);
		getContentPane().removeAll();
		setSize(35+num*65,110+40*num);
		setContentPane(Jeu);
		repaint();
		revalidate();

	
		   }
    }//GEN-LAST:event_jButton3ActionPerformed
    private void jButton4ActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	setVisible(false);
        dispose();
	}

    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}

