package Interface;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.NumberFormat;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JFrame;
import javax.swing.text.NumberFormatter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class SaisieIa extends javax.swing.JFrame {


    private int i=0;
	
	public SaisieIa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

	private void initComponents() {

        this.setResizable(false);

        jLabel2 = new javax.swing.JLabel();
        JFrame jFrame1 = new javax.swing.JFrame();
        NumberFormat format = NumberFormat.getInstance();
        NumberFormatter formatter = new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setMinimum(0);
        formatter.setMaximum(20);
        formatter.setAllowsInvalid(false);
        formatter.setCommitsOnValidEdit(true);
        JFormattedTextField textField = new JFormattedTextField(formatter);
		textField.setColumns(10);
		
		
		 javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
	        jFrame1.getContentPane().setLayout(jFrame1Layout);
	        jFrame1Layout.setHorizontalGroup(
	            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 400, Short.MAX_VALUE)
	        );
    		
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        
        JPanel jp= new JPanel();
        jp.add(textField);
 
        JLabel jt = new JLabel("<html><span style=color:#FFFFFF>Veuillez taper un nombre de lignes (Entre 0 et 20) :</span></html>");
        JPanel jp2= new JPanel();
        jp2.add(jt);
        
        jLabel2.setIcon(new ImageIcon(getClass().getResource("Capture.PNG"))); // NOI18N
        jLabel2.add(jp2);
        jp2.setBounds(200, 140, 400, 30); 
        jp2.setOpaque(false);
        setContentPane(jLabel2);
        jLabel2.setBounds(0, -10, 800, 440);
        
        getContentPane().add(jp);
        jp.setOpaque(false);
        jp.setBounds(318, 190, 160, 35);   
 
        
        JButton jButton3 = new javax.swing.JButton();
        
        jButton3.setText("Precedent");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }

			private void jButton3ActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				int x,y;
		    	JFrame win=new Acceuil();
				x=getX();
				y=getY();
				setVisible(false);		
				win.setSize(800,450);
		        win.setLocation(x, y);
				win.setVisible(true);
				dispose();
			}
        });
        setLayout(null);
        jLabel2.add(jButton3);
        jButton3.setBounds(320, 260, 160,30);
        
        KeyListener keyListener = new KeyListener() {
    	@Override
    	public void keyTyped(KeyEvent e) {
    		// TODO Auto-generated method stub
    		
    	}

    	@Override
    	public void keyPressed(KeyEvent e) {
    		
    		if(e.getKeyCode() == KeyEvent.VK_ENTER) {  
    			InterfaceAvecC.init_plateau(Integer.parseInt(textField.getText()));
    			int x,y;
    	    	JFrame win=new Choix1();
    			x=getX();
    			y=getY();
    			setVisible(false);
    			win.setSize(getSize());
    	        win.setLocation(x, y);
    			win.setVisible(true);
    		}
    	}

    	@Override
    	public void keyReleased(KeyEvent e) {
    		// TODO Auto-generated method stub
    		
    	}};
        
        textField.addKeyListener(keyListener);
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Saisie().setVisible(true);
           }       
        }); 
   }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}