package Interface;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.NumberFormat;
import java.util.Random;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.text.NumberFormatter;

public class Choix1  extends javax.swing.JFrame {


    private int i=0;
	
	public Choix1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

	private void initComponents() {
		
        this.setResizable(false);
        jLabel2 = new javax.swing.JLabel();
        JFrame jFrame1 = new javax.swing.JFrame();

		
		
		 javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
	        jFrame1.getContentPane().setLayout(jFrame1Layout);
	        jFrame1Layout.setHorizontalGroup(
	            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 400, Short.MAX_VALUE)
	        );
    		
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

 
        JLabel jt = new JLabel("<html><span style=color:#FFFFFF>Definir qui commence la partie :</span></html>");
        JPanel jp2= new JPanel();
        JPanel jp3= new JPanel();
        jp3.add(jt);
        jp3.setVisible(true);
        jp3.setOpaque(false);
        jp3.setBounds(240, 80, 300, 50);
        
        jLabel2.setIcon(new ImageIcon(getClass().getResource("Capture.PNG"))); // NOI18N
        jLabel2.add(jp2);
        jLabel2.add(jp3);
        jp2.setBounds(192, 140, 400, 30); 
        jp2.setOpaque(false);
        setContentPane(jLabel2);
        jLabel2.setBounds(0, -10, 800, 440);
        
        JButton jButton1 = new javax.swing.JButton();
        JButton jButton2 = new javax.swing.JButton();
        JButton jButton3 = new javax.swing.JButton();
        JButton jButton4 = new javax.swing.JButton();
        
        jButton3.setText("Precedent");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }

			private void jButton3ActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				int x,y;
		    	JFrame win=new SaisieIa();
				x=getX();
				y=getY();
				setVisible(false);		
				win.setSize(getSize());
		        win.setLocation(x, y);
				win.setVisible(true);
				dispose();
			}
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(310, 300, 160, 35);
        
        jButton1.setText("Adversaire");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }

			private void jButton1ActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				InterfaceAvecC.init_ia(1,0);
				int x,y;
		    	JFrame win=new Choix2();
				x=getX();
				y=getY();
				setVisible(false);		
				win.setSize(getSize());
		        win.setLocation(x, y);
				win.setVisible(true);
				dispose();
			}
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 180, 200, 35);

        jButton2.setText("Hasard");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }

			private void jButton2ActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				Random rand = new Random();
				int nombreAleatoire = rand.nextInt(2 - 1 + 1) + 1;
				InterfaceAvecC.init_ia(nombreAleatoire,0);
				int x,y;
		    	JFrame win=new Choix2();
				x=getX();
				y=getY();
				setVisible(false);		
				win.setSize(getSize());
		        win.setLocation(x, y);
				win.setVisible(true);
				dispose();
			}
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 240, 200, 35);
        
        jButton4.setText("Joueur");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }

			private void jButton1ActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				InterfaceAvecC.init_ia(2,0);
				int x,y;
		    	JFrame win=new Choix2();
				x=getX();
				y=getY();
				setVisible(false);		
				win.setSize(getSize());
		        win.setLocation(x, y);
				win.setVisible(true);
				dispose();
			}
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(290, 120, 200, 35);
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Saisie().setVisible(true);
           }       
        }); 
   }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}

